Proxy protocol header
warlock-labs/postel pull request #3
Opened 2023-10-12 15:12 UTC by megsdevs

VAL-1250

2023-10-13 02:17 UTC, 0xAlcibiades requested changes
Just the one change and will check back on the v1 support.

2023-10-13 02:17 UTC, 0xAlcibiades commented on .gitignore
> +.idea/
Redundant/already here.

2023-10-13 02:26 UTC, 0xAlcibiades commented
https://github.com/programatik29/axum-server/pull/89 - original PR/feedback for ref.

2023-10-13 02:27 UTC, 0xAlcibiades commented on src/tls_rustls/mod.rs
> +pub(crate) mod tests {
Why public crate for a test?

2023-10-13 02:27 UTC, 0xAlcibiades requested changes

2023-10-13 02:27 UTC, 0xAlcibiades commented on src/tls_openssl/mod.rs
> +pub(crate) mod tests {
Why?

2023-10-13 03:03 UTC, dbelv requested changes

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/future.rs
> +
```suggestion
```

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +//!    // Can configure if you want different from the default of 5 seconds, otherwise None.
```suggestion
//!    // Configurable timeout. If no timeout is passed to the `enable_proxy_protocol` call a default timeout of 5 seconds is used. None will disable the timeout.
```

I'm not sure if the above is correct based on the wording of the comment. Is it None will disable or use the default?

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +/// The maximum length of a header in bytes.
It would be worth referencing the documentation here as to how you came about these numbers

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +    let mut buffer = [0; DEFAULT_BUFFER_LEN];
The wording of `DEFAULT_BUFFER_LEN` is confusing here, you don't change the buffer length at any stage (this would also bring a realloc event since its a slice), maybe `READ_BUFFER_LEN` is better suited since that's all its being used for in this context.

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +            stream.read_exact(&mut buffer[i..i + 1]).await?;
Maybe 

`buffer[i] = stream.read_u8().await?;`

Would be clearer in this case that you're simply now reading one byte at a time

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +            // Switch to dynamic buffer is header is too long. V2 has no maximum length.
```suggestion
            // Switch to dynamic buffer if header is too long. V2 has no maximum length.
```

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +            }
So its going to be more efficient (and in my view more readable) to avoid the branching here, given you are basically doing the same functionality under both branches, to just always eat the cost of the initial allocation vs the double branch and maybe allocation cost.

I would recommend to simply move everything into the dynamic_buffer, with a comment explaining why it was done this way over the current implementation.

This can also simplify the logic below by moving the parsing into the if-else statement and returning the header.

2023-10-13 03:03 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +                &forwarded_string
```suggestion
                forwarded_string
```

2023-10-13 03:03 UTC, dbelv commented on src/server.rs
> +    time::Duration,
Unused

2023-10-13 03:05 UTC, dbelv commented on src/tls_rustls/mod.rs
> +pub(crate) mod tests {
It allows other test modules to import the public functions

2023-10-13 03:12 UTC, 0xAlcibiades commented
Yes, I was more looking for a comment here on the why of why they are exported in code. Should have made that more clear.

> On Oct 12, 2023, at 23:05, Dave Belvedere ***@***.***> wrote:
>
> @dbelv commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [src/tls_rustls/mod.rs](https://github.com/valorem-labs-inc/hyper-server/pull/3#discussion_r1357705188):
>
>> @@ -303,7 +303,7 @@ async fn config_from_pem_file(
>  }
>
>  #[cfg(test)]
> -mod tests {
> +pub(crate) mod tests {
>
> It allows other test modules to import the public functions
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/valorem-labs-inc/hyper-server/pull/3#discussion_r1357705188), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AVOT3C3XSBQ3LOTTW5ZOUQLX7CVYNANCNFSM6AAAAAA55Y5FDA).
> You are receiving this because your review was requested.Message ID: ***@***.***>

2023-10-13 15:40 UTC, megsdevs commented on src/tls_openssl/mod.rs
> +pub(crate) mod tests {
so i can use in the proxy tests

2023-10-13 15:41 UTC, megsdevs commented on .gitignore
> +.idea/
where is is already there

2023-10-13 15:41 UTC, megsdevs commented on src/proxy_protocol/mod.rs
> +//!    // Can configure if you want different from the default of 5 seconds, otherwise None.
None will use the default

2023-10-13 15:51 UTC, megsdevs commented on src/proxy_protocol/mod.rs
> +/// The maximum length of a header in bytes.
the spec is provided at the top. i would say that is enough

2023-10-13 15:58 UTC, megsdevs commented on src/proxy_protocol/mod.rs
> +    let mut buffer = [0; DEFAULT_BUFFER_LEN];
done

2023-10-13 16:00 UTC, megsdevs commented on src/proxy_protocol/mod.rs
> +            stream.read_exact(&mut buffer[i..i + 1]).await?;
good suggestion. done

2023-10-13 16:12 UTC, megsdevs commented on src/server.rs
> +    time::Duration,
which?

2023-10-13 16:44 UTC, megsdevs commented on src/proxy_protocol/mod.rs
> +                &forwarded_string
done

2023-10-13 20:40 UTC, megsdevs commented on src/proxy_protocol/mod.rs
> +            }
i did some refactoring, but using a fixed length buffer is more efficient given this is done for every request, and no resizing of a vector needed, then only the 0.0001% would need the dynamic buffer

2023-10-14 00:30 UTC, 0xAlcibiades approved these changes

2023-10-14 00:30 UTC, merged

2023-10-17 00:21 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +/// The maximum length of a header in bytes.
So given though the spec is provided references are also better - these are comments, you want to be overly verbose in context.

2023-10-17 00:23 UTC, dbelv commented on src/proxy_protocol/mod.rs
> +            }
That context is important for the reader - if the dynamic buffer situation is 0.0001% then it should be there somewhere. Otherwise readers/coders will assume it can be 50/50 or even that its tilted to the dynamic buffer and rework it for that scenario

2023-10-17 00:24 UTC, dbelv commented on src/server.rs
> +    time::Duration,
time::Duration